#pragma checksum "..\..\..\DuPopup.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B3636F29290085EFE8A72908ABC88E70EF8B022E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Du;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Du {
    
    
    /// <summary>
    /// DuPopup
    /// </summary>
    public partial class DuPopup : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 8 "..\..\..\DuPopup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Du.DuPopup Popup;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\DuPopup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border brdrOuter;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\DuPopup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border brdrInner;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\DuPopup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel dpnlContent;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\DuPopup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblkContentTitle;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\DuPopup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblkContentBody;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\DuPopup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel dpnlActionButtons;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\DuPopup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAction01;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\DuPopup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAction02;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\DuPopup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAction03;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.8.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Du;V0.0.10.0;component/dupopup.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\DuPopup.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.8.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Popup = ((Du.DuPopup)(target));
            return;
            case 2:
            this.brdrOuter = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.brdrInner = ((System.Windows.Controls.Border)(target));
            return;
            case 4:
            this.dpnlContent = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 5:
            this.tblkContentTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.tblkContentBody = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.dpnlActionButtons = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 8:
            this.btnAction01 = ((System.Windows.Controls.Button)(target));
            
            #line 84 "..\..\..\DuPopup.xaml"
            this.btnAction01.Click += new System.Windows.RouteDeventHandler(this.BtnAction01_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.btnAction02 = ((System.Windows.Controls.Button)(target));
            
            #line 94 "..\..\..\DuPopup.xaml"
            this.btnAction02.Click += new System.Windows.RouteDeventHandler(this.BtnAction02_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.btnAction03 = ((System.Windows.Controls.Button)(target));
            
            #line 104 "..\..\..\DuPopup.xaml"
            this.btnAction03.Click += new System.Windows.RouteDeventHandler(this.BtnAction03_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

