#pragma checksum "..\..\..\DuSplash.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "C88D4F35A592581868FED6DD55A007D987E9A963"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Du;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Du {
    
    
    /// <summary>
    /// DuSplash
    /// </summary>
    public partial class DuSplash : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 7 "..\..\..\DuSplash.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Du.DuSplash Splash;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\DuSplash.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border brdrOuter;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\DuSplash.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border brdrInner;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\DuSplash.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel dpnlContent;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\DuSplash.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblkContentTitle;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\DuSplash.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblAppVersion;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\DuSplash.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblkContentSubTitle;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\DuSplash.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblkContentBody;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\DuSplash.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblkContentStatusUpdate;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\..\DuSplash.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel dpnlActionButtons;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\DuSplash.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAction01;
        
        #line default
        #line hidden
        
        
        #line 120 "..\..\..\DuSplash.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAction02;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\..\DuSplash.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAction03;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.8.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Du;V0.0.10.0;component/dusplash.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\DuSplash.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.8.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Splash = ((Du.DuSplash)(target));
            return;
            case 2:
            this.brdrOuter = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.brdrInner = ((System.Windows.Controls.Border)(target));
            return;
            case 4:
            this.dpnlContent = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 5:
            this.tblkContentTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.lblAppVersion = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.tblkContentSubTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.tblkContentBody = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.tblkContentStatusUpdate = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.dpnlActionButtons = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 11:
            this.btnAction01 = ((System.Windows.Controls.Button)(target));
            
            #line 116 "..\..\..\DuSplash.xaml"
            this.btnAction01.Click += new System.Windows.RouteDeventHandler(this.BtnAction01_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.btnAction02 = ((System.Windows.Controls.Button)(target));
            
            #line 126 "..\..\..\DuSplash.xaml"
            this.btnAction02.Click += new System.Windows.RouteDeventHandler(this.BtnAction02_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.btnAction03 = ((System.Windows.Controls.Button)(target));
            
            #line 136 "..\..\..\DuSplash.xaml"
            this.btnAction03.Click += new System.Windows.RouteDeventHandler(this.BtnAction03_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

